### ISSUE TITLE
support for tar.xz

### ISSUE THREAD

**Issue by lo-fo** [pinterest/PodToBUILD#108]
**Error message**   
`Fatal error: Cannot extract files other than .zip or .tar`

**BUILD rule** 
```
new_pod_repository(
    name = "VLCKit",
    url = "https://download.videolan.org/pub/cocoapods/prod/MobileVLCKit-3.3.9-1a7bd97-03d4f115e0.tar.xz",
    podspec_url = "Packaging/podspecs/MobileVLCKit.podspec"
)
```

**Comment by rahul-malik** [comment]
@lo-fo - This should be straightforward to add if you just add another case to the extraction logic here https://github.com/pinterest/PodToBUILD/blob/bf92e6bbe939cdfdaf176129ac67bebd454ff241/Sources/RepoToolsCore/RepoActions.swift#L431

Happy to review a PR if you can get one up
