### ISSUE TITLE
In copts attribute of objc_library rule $(BUILD_DIR) not defined

### ISSUE THREAD

**Issue by mapleyuan** [pinterest/PodToBUILD#110]
Hi guys,
I have transfer pod to build, but i got this error. I think it is cause by the "$(BUILD_DIR)" from Pod inner, but I do not have any idea to fix it. 

Analyzing: target //mediapipe/examples/ios/facedetectioncpu:FaceDetectionCpuApp (1 packages loaded, 0 targets configured)
ERROR: /private/var/tmp/_bazel_ali/18ba3966ddbbfd8096433355d3c643f4/external/xxx/BUILD:790:11: in copts attribute of objc_library rule @xxx//:aarch64_cxx: $(BUILD_DIR) not defined

**Comment by rahul-malik** [comment]
Can you post the pod spec and generated build file?

**Comment by mapleyuan** [comment]
hi @rahul-malik ,thanks for your reply. The problem was solved(the third-party framework wasn't 64-bit)
