### ISSUE TITLE
License text should substitute "<" ">" to ensure we generate a valid plist

### ISSUE THREAD

**Issue by rahul-malik** [pinterest/PodToBUILD#15]
Currently there are characters that can create invalid plists. These should either be escaped or replaced with something that will ensure the acknowledgement plist we generate is still valid.

**Comment by rahul-malik** [comment]
Here is a more complete list
https://en.wikipedia.org/wiki/XML#Escaping

**Comment by jerrymarino** [comment]
@rahul-malik - closing this out now, as it was fixed in the recent PR 🚀
