### ISSUE TITLE
make build-test fails with Xcode 12

### ISSUE THREAD

**Issue by dgcoffman** [pinterest/PodToBUILD#173]
Because it can't compile PINCache https://github.com/pinterest/PINRemoteImage/issues/566

https://github.com/pinterest/PINCache/issues/304

Looks like it has been fixed in 3.0.3 -- this repo should be updated to use latest.

**Comment by dgcoffman** [comment]
I'll fix in my fork and open a PR soonish https://github.com/dgcoffman/PodToBUILD/pull/1/commits/bd4fb4191d30e56a8d7480c8ee6415a3a311c6da

**Comment by jparise** [comment]
Resolved by #174
