### ISSUE TITLE
"PINCache+PINRemoteImageCaching.h" file not found

### ISSUE THREAD

**Issue by baveku** [pinterest/PodToBUILD#189]
I can't build Texture 3.0.0 because PINRemoteImage doesn't have PINCache+PINRemoteImageCaching.h file.

How can I fix it?
```bash
bazel run @rules_pods//:update_pods --apple_platform_type=ios -- --src_root /Users/admin/Workspace/Project/prozer/Prozer
INFO: Analyzed target @rules_pods//:update_pods (16 packages loaded, 144 targets configured).
INFO: Found 1 target...
Target @rules_pods//bin:update_pods up-to-date:
  bazel-bin/external/rules_pods/bin/update_pods
INFO: Elapsed time: 2.331s, Critical Path: 0.02s
INFO: 4 processes: 4 internal.
INFO: Build completed successfully, 4 total actions
INFO: Build completed successfully, 4 total actions
Updating pods in /Users/admin/Workspace/Project/prozer/Prozer
Building PodToBUILD dependencies...
running: make release
skipping build..

Updating Pod Texture...
Updating Pod PINRemoteImage...
Updating Pod PINOperation...
Updating Pod PINCache...
Updating Pod Moya...
Updating Pod Alamofire...
bazel fetch :*
INFO: All external dependencies fetched successfully.
Loading: 14 packages loaded
bazel build //Prozer:Prozer 
INFO: Analyzed target //Prozer:Prozer (24 packages loaded, 3780 targets configured).
INFO: Found 1 target...
ERROR: /Users/admin/Workspace/Project/prozer/Prozer/Vendor/PINRemoteImage/BUILD.bazel:227:13: Compiling Vendor/PINRemoteImage/Source/Classes/PINRemoteImageManager.m failed: (Aborted): wrapped_clang failed: error executing command external/local_config_cc/wrapped_clang -arch x86_64 '-D_FORTIFY_SOURCE=1' -fstack-protector -fcolor-diagnostics -Wall -Wthread-safety -Wself-assign -fno-omit-frame-pointer -O0 -DDEBUG ... (remaining 64 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
In file included from Vendor/PINRemoteImage/Source/Classes/PINRemoteImageManager.m:22:
./Vendor/PINRemoteImage/Source/Classes/include/PINRemoteImage.h:11:11: fatal error: 'PINCache+PINRemoteImageCaching.h' file not found
  #import "PINCache+PINRemoteImageCaching.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
Error in child process '/usr/bin/xcrun'. 1
Target //Prozer:Prozer failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 31.398s, Critical Path: 14.28s
INFO: 199 processes: 60 internal, 139 darwin-sandbox.
FAILED: Build did NOT complete successfully
make: *** [build] Error 1
```

**Comment by Jacky-LinPeng** [comment]
I have the same problem, how did you solve it?

**Comment by baveku** [comment]
> I have the same problem, how did you solve it?

because you need add deps to PINCore
`new_pod_repository(
    name = "PINRemoteImage",
    generate_header_map = True,
    generate_module_map = False,
    url = "https://github.com/pinterest/PINRemoteImage/archive/3.0.3.zip",
    # PINRemoteImage_Core conditionally compiles in PINCache based on these
    # headers
    user_options = [
        "PINRemoteImage_Core.deps += //Vendor/PINCache:PINCache",
    ],
)`

**Comment by Jacky-LinPeng** [comment]
> > I have the same problem, how did you solve it?
> 
> because you need add deps PINCache to Core
> 
> ```
> new_pod_repository(
>     name = "PINRemoteImage",
>     generate_header_map = True,
>     generate_module_map = False,
>     url = "https://github.com/pinterest/PINRemoteImage/archive/3.0.3.zip",
>     # PINRemoteImage_Core conditionally compiles in PINCache based on these
>     # headers
>     user_options = [
>         "PINRemoteImage_Core.deps += //Vendor/PINCache:PINCache",
>     ],
> )
> ```
> 
> I wrote an example in: https://github.com/baveku/bazel-ios-example I hope that will help you.



> > I have the same problem, how did you solve it?
> 
> because you need add deps PINCache to Core
> 
> ```
> new_pod_repository(
>     name = "PINRemoteImage",
>     generate_header_map = True,
>     generate_module_map = False,
>     url = "https://github.com/pinterest/PINRemoteImage/archive/3.0.3.zip",
>     # PINRemoteImage_Core conditionally compiles in PINCache based on these
>     # headers
>     user_options = [
>         "PINRemoteImage_Core.deps += //Vendor/PINCache:PINCache",
>     ],
> )
> ```
> 
> I wrote an example in: https://github.com/baveku/bazel-ios-example I hope that will help you.

Thanks so much!!!

**Comment by Jacky-LinPeng** [comment]
Hi, here is  my issues: 

[issues](https://github.com/pinterest/PodToBUILD/issues/211)

Is there something I'm using wrong? Hope to get your help
