### ISSUE TITLE
Swift Library cannot import ObjC_Library

### ISSUE THREAD

**Issue by baveku** [pinterest/PodToBUILD#198]
I can't import Objc_Library (Texture, IGListKit, PINRemoteImage) inside swift_library
```
load("@build_bazel_rules_swift//swift:swift.bzl", "swift_library")

swift_library(
    name = "IBCs",
    srcs = glob([
        "Classes/**/*.swift",
    ]),
    module_name = "IBCs",
    visibility = ["//visibility:public"],
    deps = [
        "//Vendor/ObjectMapper",
        "//Vendor/Texture:Texture",
        "//third_party/RxSwift",
        "//third_party/RxSwift:RxCocoa",
    ],
)
```

with ObjectMapper + RxSwift + RxCocoa, it's worked, but with Texture alway "no such module "Texture""

**Comment by Jacky-LinPeng** [comment]
I also met the same problem, how did you solve it?

**Comment by baveku** [comment]
> I also met the same problem, how did you solve it?

some pod cannot use PodToBuild, so I found a solution to solve it
You can follow by link:
https://tulipemoutarde.be/posts/bazel-for-mobile-apps-part-2/

This blog help me alot. Maybe you too,
