### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by stristr** [pinterest/PodToBUILD#70]
Hello! There have been quite a few bugfixes merged since the 2018-10-31 pre-release 0.18.0-95fd009. Can we please get a new pre-release up on GitHub?

I'm using `local_repository` with a locally-built checkout with my project right now, and because the Git repository doesn't store the Swift binaries (`Compiler` and `RepoTools`), I think we can't use `git_repository` on its own.

**Comment by rahul-malik** [comment]
@stristr - I just manually put up a new release as of what is in master right now. I built the relevant binaries which should make it easier to upgrade 
https://github.com/pinterest/PodToBUILD/releases/tag/0.22.0-ee8466e

**Comment by stristr** [comment]
Thanks @rahul-malik. It looks like the release you just cut is missing the actual binary release though—there's no artifact at https://github.com/pinterest/PodToBUILD/releases/download/0.22.0-ee8466e/PodToBUILD.zip.

**Comment by rahul-malik** [comment]
@stristr - Looks like Github failed to upload the attachment, just fixed it!

**Comment by stristr** [comment]
Awesome—thank you, @rahul-malik! It's working now.
